apiVersion: hyper.io/v1alpha1
kind: HyperConfig
metadata:
  name: global-engine-config
spec:
  serverAddress: "0.0.0.0:9001"
  maxConcurrentStreams: 1024
  logLevel: "DEBUG"
  targetNamespace: "hyper-system"
