//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyStatusCheck) DeepCopyInto(out *ApiKeyStatusCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyStatusCheck.
func (in *ApiKeyStatusCheck) DeepCopy() *ApiKeyStatusCheck {
	if in == nil {
		return nil
	}
	out := new(ApiKeyStatusCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyOutputMapping) DeepCopyInto(out *ApiKeyOutputMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyOutputMapping.
func (in *ApiKeyOutputMapping) DeepCopy() *ApiKeyOutputMapping {
	if in == nil {
		return nil
	}
	out := new(ApiKeyOutputMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyFilterSpec) DeepCopyInto(out *ApiKeyFilterSpec) {
	*out = *in
	if in.KeyNames != nil {
		in, out := &in.KeyNames, &out.KeyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.StatusCheck = in.StatusCheck
	if in.OutputMappings != nil {
		in, out := &in.OutputMappings, &out.OutputMappings
		*out = make([]ApiKeyOutputMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyFilterSpec.
func (in *ApiKeyFilterSpec) DeepCopy() *ApiKeyFilterSpec {
	if in == nil {
		return nil
	}
	out := new(ApiKeyFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyFilterStatus) DeepCopyInto(out *ApiKeyFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyFilterStatus.
func (in *ApiKeyFilterStatus) DeepCopy() *ApiKeyFilterStatus {
	if in == nil {
		return nil
	}
	out := new(ApiKeyFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyFilter) DeepCopyInto(out *ApiKeyFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyFilter.
func (in *ApiKeyFilter) DeepCopy() *ApiKeyFilter {
	if in == nil {
		return nil
	}
	out := new(ApiKeyFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiKeyFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyFilterList) DeepCopyInto(out *ApiKeyFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiKeyFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyFilterList.
func (in *ApiKeyFilterList) DeepCopy() *ApiKeyFilterList {
	if in == nil {
		return nil
	}
	out := new(ApiKeyFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiKeyFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrelationIdFilter) DeepCopyInto(out *CorrelationIdFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrelationIdFilter.
func (in *CorrelationIdFilter) DeepCopy() *CorrelationIdFilter {
	if in == nil {
		return nil
	}
	out := new(CorrelationIdFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CorrelationIdFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrelationIdFilterList) DeepCopyInto(out *CorrelationIdFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CorrelationIdFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrelationIdFilterList.
func (in *CorrelationIdFilterList) DeepCopy() *CorrelationIdFilterList {
	if in == nil {
		return nil
	}
	out := new(CorrelationIdFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CorrelationIdFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrelationIdFilterSpec) DeepCopyInto(out *CorrelationIdFilterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrelationIdFilterSpec.
func (in *CorrelationIdFilterSpec) DeepCopy() *CorrelationIdFilterSpec {
	if in == nil {
		return nil
	}
	out := new(CorrelationIdFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrelationIdFilterStatus) DeepCopyInto(out *CorrelationIdFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrelationIdFilterStatus.
func (in *CorrelationIdFilterStatus) DeepCopy() *CorrelationIdFilterStatus {
	if in == nil {
		return nil
	}
	out := new(CorrelationIdFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyFilter) DeepCopyInto(out *DenyFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyFilter.
func (in *DenyFilter) DeepCopy() *DenyFilter {
	if in == nil {
		return nil
	}
	out := new(DenyFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DenyFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyFilterList) DeepCopyInto(out *DenyFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DenyFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyFilterList.
func (in *DenyFilterList) DeepCopy() *DenyFilterList {
	if in == nil {
		return nil
	}
	out := new(DenyFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DenyFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyFilterSpec) DeepCopyInto(out *DenyFilterSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyFilterSpec.
func (in *DenyFilterSpec) DeepCopy() *DenyFilterSpec {
	if in == nil {
		return nil
	}
	out := new(DenyFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyFilterStatus) DeepCopyInto(out *DenyFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyFilterStatus.
func (in *DenyFilterStatus) DeepCopy() *DenyFilterStatus {
	if in == nil {
		return nil
	}
	out := new(DenyFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyMatchConfig) DeepCopyInto(out *DenyMatchConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResponseHeaders != nil {
		in, out := &in.ResponseHeaders, &out.ResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NotHeaders != nil {
		in, out := &in.NotHeaders, &out.NotHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NotResponseHeaders != nil {
		in, out := &in.NotResponseHeaders, &out.NotResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyMatchConfig.
func (in *DenyMatchConfig) DeepCopy() *DenyMatchConfig {
	if in == nil {
		return nil
	}
	out := new(DenyMatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Descriptor) DeepCopyInto(out *Descriptor) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]DescriptorEntryDef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Descriptor.
func (in *Descriptor) DeepCopy() *Descriptor {
	if in == nil {
		return nil
	}
	out := new(Descriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescriptorEntryDef) DeepCopyInto(out *DescriptorEntryDef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescriptorEntryDef.
func (in *DescriptorEntryDef) DeepCopy() *DescriptorEntryDef {
	if in == nil {
		return nil
	}
	out := new(DescriptorEntryDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicCost) DeepCopyInto(out *DynamicCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicCost.
func (in *DynamicCost) DeepCopy() *DynamicCost {
	if in == nil {
		return nil
	}
	out := new(DynamicCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterReference) DeepCopyInto(out *FilterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterReference.
func (in *FilterReference) DeepCopy() *FilterReference {
	if in == nil {
		return nil
	}
	out := new(FilterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderModifierFilter) DeepCopyInto(out *HeaderModifierFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderModifierFilter.
func (in *HeaderModifierFilter) DeepCopy() *HeaderModifierFilter {
	if in == nil {
		return nil
	}
	out := new(HeaderModifierFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeaderModifierFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderModifierFilterList) DeepCopyInto(out *HeaderModifierFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeaderModifierFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderModifierFilterList.
func (in *HeaderModifierFilterList) DeepCopy() *HeaderModifierFilterList {
	if in == nil {
		return nil
	}
	out := new(HeaderModifierFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeaderModifierFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderModifierFilterSpec) DeepCopyInto(out *HeaderModifierFilterSpec) {
	*out = *in
	in.Upstream.DeepCopyInto(&out.Upstream)
	in.Downstream.DeepCopyInto(&out.Downstream)
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderModifierFilterSpec.
func (in *HeaderModifierFilterSpec) DeepCopy() *HeaderModifierFilterSpec {
	if in == nil {
		return nil
	}
	out := new(HeaderModifierFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderModifierFilterStatus) DeepCopyInto(out *HeaderModifierFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderModifierFilterStatus.
func (in *HeaderModifierFilterStatus) DeepCopy() *HeaderModifierFilterStatus {
	if in == nil {
		return nil
	}
	out := new(HeaderModifierFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderOptions) DeepCopyInto(out *HeaderOptions) {
	*out = *in
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderOptions.
func (in *HeaderOptions) DeepCopy() *HeaderOptions {
	if in == nil {
		return nil
	}
	out := new(HeaderOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperChain) DeepCopyInto(out *HyperChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperChain.
func (in *HyperChain) DeepCopy() *HyperChain {
	if in == nil {
		return nil
	}
	out := new(HyperChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperChainList) DeepCopyInto(out *HyperChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperChainList.
func (in *HyperChainList) DeepCopy() *HyperChainList {
	if in == nil {
		return nil
	}
	out := new(HyperChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperChainSpec) DeepCopyInto(out *HyperChainSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]FilterReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperChainSpec.
func (in *HyperChainSpec) DeepCopy() *HyperChainSpec {
	if in == nil {
		return nil
	}
	out := new(HyperChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperChainStatus) DeepCopyInto(out *HyperChainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperChainStatus.
func (in *HyperChainStatus) DeepCopy() *HyperChainStatus {
	if in == nil {
		return nil
	}
	out := new(HyperChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperConfig) DeepCopyInto(out *HyperConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperConfig.
func (in *HyperConfig) DeepCopy() *HyperConfig {
	if in == nil {
		return nil
	}
	out := new(HyperConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperConfigList) DeepCopyInto(out *HyperConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperConfigList.
func (in *HyperConfigList) DeepCopy() *HyperConfigList {
	if in == nil {
		return nil
	}
	out := new(HyperConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperConfigSpec) DeepCopyInto(out *HyperConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperConfigSpec.
func (in *HyperConfigSpec) DeepCopy() *HyperConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HyperConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperConfigStatus) DeepCopyInto(out *HyperConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperConfigStatus.
func (in *HyperConfigStatus) DeepCopy() *HyperConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HyperConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRedis) DeepCopyInto(out *HyperRedis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRedis.
func (in *HyperRedis) DeepCopy() *HyperRedis {
	if in == nil {
		return nil
	}
	out := new(HyperRedis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperRedis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRedisList) DeepCopyInto(out *HyperRedisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperRedis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRedisList.
func (in *HyperRedisList) DeepCopy() *HyperRedisList {
	if in == nil {
		return nil
	}
	out := new(HyperRedisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperRedisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRedisSpec) DeepCopyInto(out *HyperRedisSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRedisSpec.
func (in *HyperRedisSpec) DeepCopy() *HyperRedisSpec {
	if in == nil {
		return nil
	}
	out := new(HyperRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRedisStatus) DeepCopyInto(out *HyperRedisStatus) {
	*out = *in
	in.LastCheck.DeepCopyInto(&out.LastCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRedisStatus.
func (in *HyperRedisStatus) DeepCopy() *HyperRedisStatus {
	if in == nil {
		return nil
	}
	out := new(HyperRedisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRoute) DeepCopyInto(out *HyperRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRoute.
func (in *HyperRoute) DeepCopy() *HyperRoute {
	if in == nil {
		return nil
	}
	out := new(HyperRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRouteList) DeepCopyInto(out *HyperRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRouteList.
func (in *HyperRouteList) DeepCopy() *HyperRouteList {
	if in == nil {
		return nil
	}
	out := new(HyperRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRouteSpec) DeepCopyInto(out *HyperRouteSpec) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]MatchRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRouteSpec.
func (in *HyperRouteSpec) DeepCopy() *HyperRouteSpec {
	if in == nil {
		return nil
	}
	out := new(HyperRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperRouteStatus) DeepCopyInto(out *HyperRouteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperRouteStatus.
func (in *HyperRouteStatus) DeepCopy() *HyperRouteStatus {
	if in == nil {
		return nil
	}
	out := new(HyperRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchRule) DeepCopyInto(out *MatchRule) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchRule.
func (in *MatchRule) DeepCopy() *MatchRule {
	if in == nil {
		return nil
	}
	out := new(MatchRule)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputMappingSpec) DeepCopyInto(out *OutputMappingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputMappingSpec.
func (in *OutputMappingSpec) DeepCopy() *OutputMappingSpec {
	if in == nil {
		return nil
	}
	out := new(OutputMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitFilter) DeepCopyInto(out *RateLimitFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitFilter.
func (in *RateLimitFilter) DeepCopy() *RateLimitFilter {
	if in == nil {
		return nil
	}
	out := new(RateLimitFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitFilterList) DeepCopyInto(out *RateLimitFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimitFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitFilterList.
func (in *RateLimitFilterList) DeepCopy() *RateLimitFilterList {
	if in == nil {
		return nil
	}
	out := new(RateLimitFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitFilterSpec) DeepCopyInto(out *RateLimitFilterSpec) {
	*out = *in
	out.ResponseHeaders = in.ResponseHeaders
	out.DynamicCost = in.DynamicCost
	if in.HeaderMappings != nil {
		in, out := &in.HeaderMappings, &out.HeaderMappings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Descriptors != nil {
		in, out := &in.Descriptors, &out.Descriptors
		*out = make([]Descriptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitFilterSpec.
func (in *RateLimitFilterSpec) DeepCopy() *RateLimitFilterSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitFilterStatus) DeepCopyInto(out *RateLimitFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitFilterStatus.
func (in *RateLimitFilterStatus) DeepCopy() *RateLimitFilterStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisMetadataEnricherFilter) DeepCopyInto(out *RedisMetadataEnricherFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisMetadataEnricherFilter.
func (in *RedisMetadataEnricherFilter) DeepCopy() *RedisMetadataEnricherFilter {
	if in == nil {
		return nil
	}
	out := new(RedisMetadataEnricherFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisMetadataEnricherFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisMetadataEnricherFilterList) DeepCopyInto(out *RedisMetadataEnricherFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedisMetadataEnricherFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisMetadataEnricherFilterList.
func (in *RedisMetadataEnricherFilterList) DeepCopy() *RedisMetadataEnricherFilterList {
	if in == nil {
		return nil
	}
	out := new(RedisMetadataEnricherFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisMetadataEnricherFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisMetadataEnricherFilterSpec) DeepCopyInto(out *RedisMetadataEnricherFilterSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]Variable, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OutputMappings != nil {
		in, out := &in.OutputMappings, &out.OutputMappings
		*out = make([]OutputMappingSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisMetadataEnricherFilterSpec.
func (in *RedisMetadataEnricherFilterSpec) DeepCopy() *RedisMetadataEnricherFilterSpec {
	if in == nil {
		return nil
	}
	out := new(RedisMetadataEnricherFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisMetadataEnricherFilterStatus) DeepCopyInto(out *RedisMetadataEnricherFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisMetadataEnricherFilterStatus.
func (in *RedisMetadataEnricherFilterStatus) DeepCopy() *RedisMetadataEnricherFilterStatus {
	if in == nil {
		return nil
	}
	out := new(RedisMetadataEnricherFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseHeaders) DeepCopyInto(out *ResponseHeaders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseHeaders.
func (in *ResponseHeaders) DeepCopy() *ResponseHeaders {
	if in == nil {
		return nil
	}
	out := new(ResponseHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSuccessRules) DeepCopyInto(out *AuthSuccessRules) {
	*out = *in
	if in.UpstreamHeadersToAdd != nil {
		in, out := &in.UpstreamHeadersToAdd, &out.UpstreamHeadersToAdd
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpstreamHeadersToRemove != nil {
		in, out := &in.UpstreamHeadersToRemove, &out.UpstreamHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSuccessRules.
func (in *AuthSuccessRules) DeepCopy() *AuthSuccessRules {
	if in == nil {
		return nil
	}
	out := new(AuthSuccessRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFailureRules) DeepCopyInto(out *AuthFailureRules) {
	*out = *in
	if in.DownstreamPassThroughHeaders != nil {
		in, out := &in.DownstreamPassThroughHeaders, &out.DownstreamPassThroughHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFailureRules.
func (in *AuthFailureRules) DeepCopy() *AuthFailureRules {
	if in == nil {
		return nil
	}
	out := new(AuthFailureRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineRulesSpec) DeepCopyInto(out *EngineRulesSpec) {
	*out = *in
	if in.ForwardHeaders != nil {
		in, out := &in.ForwardHeaders, &out.ForwardHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.OnSuccess.DeepCopyInto(&out.OnSuccess)
	in.OnFailure.DeepCopyInto(&out.OnFailure)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineRulesSpec.
func (in *EngineRulesSpec) DeepCopy() *EngineRulesSpec {
	if in == nil {
		return nil
	}
	out := new(EngineRulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarContainerSpec) DeepCopyInto(out *SidecarContainerSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarContainerSpec.
func (in *SidecarContainerSpec) DeepCopy() *SidecarContainerSpec {
	if in == nil {
		return nil
	}
	out := new(SidecarContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthFilterSpec) DeepCopyInto(out *ExternalAuthFilterSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	in.EngineRules.DeepCopyInto(&out.EngineRules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthFilterSpec.
func (in *ExternalAuthFilterSpec) DeepCopy() *ExternalAuthFilterSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthFilterStatus) DeepCopyInto(out *ExternalAuthFilterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthFilterStatus.
func (in *ExternalAuthFilterStatus) DeepCopy() *ExternalAuthFilterStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthFilter) DeepCopyInto(out *ExternalAuthFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthFilter.
func (in *ExternalAuthFilter) DeepCopy() *ExternalAuthFilter {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalAuthFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthFilterList) DeepCopyInto(out *ExternalAuthFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalAuthFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthFilterList.
func (in *ExternalAuthFilterList) DeepCopy() *ExternalAuthFilterList {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalAuthFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

