apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyper-operator
  namespace: hyper-system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1 
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: hyper-operator-sa
      containers:
        - name: manager
          image: ghcr.io/taha2samy-3/hyper-operator:sha-34cb5f99
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --metrics-bind-address=:8080
            - --leader-elect
            - --leader-elect-lease-duration=15s
            - --leader-elect-renew-deadline=10s
            - --leader-elect-retry-period=2s
            - --leader-elect-release-on-cancel=true
          env:
            - name: ENABLE_WEBHOOKS
              value: "true" # Webhooks enabled
          ports:
            - containerPort: 9443 # Default port for the webhook server
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
      terminationGracePeriodSeconds: 10