name: 'Run Tests'
description: 'Runs Go unit tests and pytest integration scenarios'

runs:
  using: 'composite'
  steps:
    - name: Set up Go Environment
      uses: ./.github/actions/setup-go-env

    - name: Run Go Unit Tests
      shell: bash
      run: task engine:test

    - name: Set up Python Environment
      uses: ./.github/actions/setup-python-env

    - name: Install Pipenv Dependencies
      shell: bash
      run: pipenv install --dev --skip-lock

    - name: Run Integration Tests
      shell: bash
      run: task test:all
