FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends git curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir grpcio grpcio-tools kubernetes

RUN git clone --depth 1 https://github.com/envoyproxy/data-plane-api.git /tmp/data-plane-api && \
    git clone --depth 1 https://github.com/googleapis/googleapis.git /tmp/googleapis && \
    git clone --depth 1 https://github.com/cncf/xds.git /tmp/xds && \
    git clone --depth 1 https://github.com/bufbuild/protoc-gen-validate.git /tmp/validate

RUN python -m grpc_tools.protoc \
    -I/tmp/data-plane-api \
    -I/tmp/googleapis \
    -I/tmp/xds \
    -I/tmp/validate \
    --python_out=. \
    --grpc_python_out=. \
    /tmp/data-plane-api/envoy/service/auth/v3/external_auth.proto \
    /tmp/data-plane-api/envoy/service/auth/v3/attribute_context.proto \
    /tmp/data-plane-api/envoy/config/core/v3/base.proto \
    /tmp/data-plane-api/envoy/config/core/v3/address.proto \
    /tmp/data-plane-api/envoy/config/core/v3/backoff.proto \
    /tmp/data-plane-api/envoy/config/core/v3/extension.proto \
    /tmp/data-plane-api/envoy/config/core/v3/socket_option.proto \
    /tmp/data-plane-api/envoy/type/v3/http_status.proto \
    /tmp/data-plane-api/envoy/type/v3/percent.proto \
    /tmp/data-plane-api/envoy/type/v3/range.proto \
    /tmp/data-plane-api/envoy/type/v3/semantic_version.proto \
    /tmp/data-plane-api/envoy/type/metadata/v3/metadata.proto \
    /tmp/data-plane-api/envoy/type/tracing/v3/custom_tag.proto

COPY mock_server.py .

EXPOSE 9001

CMD ["python", "mock_server.py"]