FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o mock-engine .

FROM debian:12-slim
WORKDIR /
COPY --from=builder /app/mock-engine .
EXPOSE 9001
ENTRYPOINT ["/mock-engine"]
