apiVersion: hyper.io/v1alpha1
kind: HyperConfig
metadata:
  name: global-engine-config
spec:
  serverAddress: "0.0.0.0:9001"
  maxConcurrentStreams: 1024
  logLevel: "DEBUG"
  redisServiceRef: "shared-redis"
  targetNamespace: "hyper-system"
  engineImage: "ghcr.io/taha2samy-3/hyper-mock-engine:1.0.0"
  fallbackChain: "chain_fallback_deny" 