// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: hypergate/identity/v1/identity.proto

// Workload identity resources streamed by the hyper-operator leader to engines
// over delta xDS (docs/design/identity-distribution.md, sections 4 and 5).

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadKind says what an IP belongs to.
type WorkloadKind int32

const (
	WorkloadKind_WORKLOAD_KIND_UNSPECIFIED WorkloadKind = 0
	// A pod IP.
	WorkloadKind_WORKLOAD_KIND_POD WorkloadKind = 1
	// A node address. hostNetwork pods share it and are not told apart.
	WorkloadKind_WORKLOAD_KIND_NODE WorkloadKind = 2
)

// Enum value maps for WorkloadKind.
var (
	WorkloadKind_name = map[int32]string{
		0: "WORKLOAD_KIND_UNSPECIFIED",
		1: "WORKLOAD_KIND_POD",
		2: "WORKLOAD_KIND_NODE",
	}
	WorkloadKind_value = map[string]int32{
		"WORKLOAD_KIND_UNSPECIFIED": 0,
		"WORKLOAD_KIND_POD":         1,
		"WORKLOAD_KIND_NODE":        2,
	}
)

func (x WorkloadKind) Enum() *WorkloadKind {
	p := new(WorkloadKind)
	*p = x
	return p
}

func (x WorkloadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hypergate_identity_v1_identity_proto_enumTypes[0].Descriptor()
}

func (WorkloadKind) Type() protoreflect.EnumType {
	return &file_hypergate_identity_v1_identity_proto_enumTypes[0]
}

func (x WorkloadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadKind.Descriptor instead.
func (WorkloadKind) EnumDescriptor() ([]byte, []int) {
	return file_hypergate_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

// Workload is the identity behind one IP. The xDS resource name is the IP.
// Type URL: type.googleapis.com/hypergate.identity.v1.Workload
type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address (IPv4 or IPv6). One resource per IP, so dual-stack pods have two.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Pod UID, which tells a reused IP apart.
	PodUid         string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Namespace      string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod            string `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	ServiceAccount string `protobuf:"bytes,5,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// spiffe://<trust-domain>/ns/<namespace>/sa/<service-account>
	SpiffeId string `protobuf:"bytes,6,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Cilium numeric security identity, 0 without Cilium.
	SecurityIdentity uint32 `protobuf:"varint,7,opt,name=security_identity,json=securityIdentity,proto3" json:"security_identity,omitempty"`
	// Pod labels on the operator's allow-list.
	Labels map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Services that have the pod as an endpoint, sorted.
	Services []*ServiceRef `protobuf:"bytes,9,rep,name=services,proto3" json:"services,omitempty"`
	// Node name (for pods: where the pod runs).
	Node string       `protobuf:"bytes,10,opt,name=node,proto3" json:"node,omitempty"`
	Kind WorkloadKind `protobuf:"varint,11,opt,name=kind,proto3,enum=hypergate.identity.v1.WorkloadKind" json:"kind,omitempty"`
	// Labels of the Cilium security identity, sorted.
	CiliumLabels  []string `protobuf:"bytes,12,rep,name=cilium_labels,json=ciliumLabels,proto3" json:"cilium_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_hypergate_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Workload) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *Workload) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *Workload) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *Workload) GetSecurityIdentity() uint32 {
	if x != nil {
		return x.SecurityIdentity
	}
	return 0
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Workload) GetServices() []*ServiceRef {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Workload) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Workload) GetKind() WorkloadKind {
	if x != nil {
		return x.Kind
	}
	return WorkloadKind_WORKLOAD_KIND_UNSPECIFIED
}

func (x *Workload) GetCiliumLabels() []string {
	if x != nil {
		return x.CiliumLabels
	}
	return nil
}

// ServiceRef names a Service.
type ServiceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRef) Reset() {
	*x = ServiceRef{}
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRef) ProtoMessage() {}

func (x *ServiceRef) ProtoReflect() protoreflect.Message {
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRef.ProtoReflect.Descriptor instead.
func (*ServiceRef) Descriptor() ([]byte, []int) {
	return file_hypergate_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Service is a Service and its cluster IPs. The xDS resource name is
// "<namespace>/<name>".
// Type URL: type.googleapis.com/hypergate.identity.v1.Service
type Service struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Cluster IPs (none for headless Services).
	ClusterIps    []string `protobuf:"bytes,3,rep,name=cluster_ips,json=clusterIps,proto3" json:"cluster_ips,omitempty"`
	Ports         []uint32 `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_hypergate_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_hypergate_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetClusterIps() []string {
	if x != nil {
		return x.ClusterIps
	}
	return nil
}

func (x *Service) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_hypergate_identity_v1_identity_proto protoreflect.FileDescriptor

const file_hypergate_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"$hypergate/identity/v1/identity.proto\x12\x15hypergate.identity.v1\"\x87\x04\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\x12'\n" +
	"\x0fservice_account\x18\x05 \x01(\tR\x0eserviceAccount\x12\x1b\n" +
	"\tspiffe_id\x18\x06 \x01(\tR\bspiffeId\x12+\n" +
	"\x11security_identity\x18\a \x01(\rR\x10securityIdentity\x12C\n" +
	"\x06labels\x18\b \x03(\v2+.hypergate.identity.v1.Workload.LabelsEntryR\x06labels\x12=\n" +
	"\bservices\x18\t \x03(\v2!.hypergate.identity.v1.ServiceRefR\bservices\x12\x12\n" +
	"\x04node\x18\n" +
	" \x01(\tR\x04node\x127\n" +
	"\x04kind\x18\v \x01(\x0e2#.hypergate.identity.v1.WorkloadKindR\x04kind\x12#\n" +
	"\rcilium_labels\x18\f \x03(\tR\fciliumLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\n" +
	"ServiceRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"r\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vcluster_ips\x18\x03 \x03(\tR\n" +
	"clusterIps\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\rR\x05ports*\\\n" +
	"\fWorkloadKind\x12\x1d\n" +
	"\x19WORKLOAD_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WORKLOAD_KIND_POD\x10\x01\x12\x16\n" +
	"\x12WORKLOAD_KIND_NODE\x10\x02BCZAgithub.com/taha2samy/hypergate/internal/identityapi/v1;identityv1b\x06proto3"

var (
	file_hypergate_identity_v1_identity_proto_rawDescOnce sync.Once
	file_hypergate_identity_v1_identity_proto_rawDescData []byte
)

func file_hypergate_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_hypergate_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_hypergate_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypergate_identity_v1_identity_proto_rawDesc), len(file_hypergate_identity_v1_identity_proto_rawDesc)))
	})
	return file_hypergate_identity_v1_identity_proto_rawDescData
}

var file_hypergate_identity_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hypergate_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hypergate_identity_v1_identity_proto_goTypes = []any{
	(WorkloadKind)(0),  // 0: hypergate.identity.v1.WorkloadKind
	(*Workload)(nil),   // 1: hypergate.identity.v1.Workload
	(*ServiceRef)(nil), // 2: hypergate.identity.v1.ServiceRef
	(*Service)(nil),    // 3: hypergate.identity.v1.Service
	nil,                // 4: hypergate.identity.v1.Workload.LabelsEntry
}
var file_hypergate_identity_v1_identity_proto_depIdxs = []int32{
	4, // 0: hypergate.identity.v1.Workload.labels:type_name -> hypergate.identity.v1.Workload.LabelsEntry
	2, // 1: hypergate.identity.v1.Workload.services:type_name -> hypergate.identity.v1.ServiceRef
	0, // 2: hypergate.identity.v1.Workload.kind:type_name -> hypergate.identity.v1.WorkloadKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hypergate_identity_v1_identity_proto_init() }
func file_hypergate_identity_v1_identity_proto_init() {
	if File_hypergate_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypergate_identity_v1_identity_proto_rawDesc), len(file_hypergate_identity_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypergate_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_hypergate_identity_v1_identity_proto_depIdxs,
		EnumInfos:         file_hypergate_identity_v1_identity_proto_enumTypes,
		MessageInfos:      file_hypergate_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_hypergate_identity_v1_identity_proto = out.File
	file_hypergate_identity_v1_identity_proto_goTypes = nil
	file_hypergate_identity_v1_identity_proto_depIdxs = nil
}
