import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar mirrors the docs/ folder; order comes from sidebar_position and
// _category_.json files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
